-- Replace POLICY_TAG_RESOURCE with your actual policy tag resource name, e.g. projects/123/locations/eu/taxonomies/456/policyTags/789
ALTER TABLE `{{project_id}}.energy_analytics.curated_usage`
ALTER COLUMN income2 SET POLICY TAG POLICY_TAG_RESOURCE,
ALTER COLUMN income3 SET POLICY TAG POLICY_TAG_RESOURCE,
ALTER COLUMN income4 SET POLICY TAG POLICY_TAG_RESOURCE,
ALTER COLUMN income5 SET POLICY TAG POLICY_TAG_RESOURCE,
ALTER COLUMN income6 SET POLICY TAG POLICY_TAG_RESOURCE,
ALTER COLUMN income7 SET POLICY TAG POLICY_TAG_RESOURCE,
ALTER COLUMN income8 SET POLICY TAG POLICY_TAG_RESOURCE,
ALTER COLUMN income9 SET POLICY TAG POLICY_TAG_RESOURCE;